// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdtktpbxzwsomykkrhtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkdGt0cGJ4endzb215a2tyaHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NDc0MzEsImV4cCI6MjA1NjIyMzQzMX0.Punx6YFQgSLRfoZm53iVr8rywYyQXfRl3rS031qDcMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);